const express = require('express');
const router = express.Router();
const { Pool } = require('pg');
const axios = require('axios');
const useragent = require('useragent');
const geoip = require('geoip-lite');

// ─── PostgreSQL Pool ──────────────────────────────────────────────────────────
const pool = new Pool({
  host:     process.env.DB_HOST,
  port:     parseInt(process.env.DB_PORT || '5432'),
  database: process.env.DB_NAME,
  user:     process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : false,
});

// ─── Helper: device type from User-Agent ─────────────────────────────────────
function getDeviceType(uaString) {
  if (/mobile|android|iphone|ipod|blackberry|opera mini|windows phone/i.test(uaString)) return 'Mobile';
  if (/ipad|tablet/i.test(uaString)) return 'Tablet';
  return 'Desktop';
}

// ─── Helper: HTML table row ───────────────────────────────────────────────────
function row(label, value) {
  return `
    <tr>
      <td style="padding:10px 16px;background:#f9fafb;font-weight:600;width:35%;border-bottom:1px solid #e5e7eb">${label}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #e5e7eb;word-break:break-all">${value || '—'}</td>
    </tr>`;
}

// ─── Helper: send mail via Brevo REST API ─────────────────────────────────────
async function sendBrevoMail(data) {
  const { country, state, city, deviceType, platform, language, timezone, referrer, currentUrl, visitedAt, ip, uaString } = data;

  const payload = {
    sender: {
      name:  process.env.BREVO_SENDER_NAME  || 'Visitor Tracker',
      email: process.env.BREVO_SENDER_EMAIL,
    },
    to: [
      {
        email: process.env.BREVO_TO_EMAIL,
        name:  process.env.BREVO_TO_NAME || 'Admin',
      },
    ],
    subject: `🌐 New Visitor — ${city || 'Unknown City'}, ${country || 'Unknown Country'}`,
    htmlContent: `
      <div style="font-family:Arial,sans-serif;max-width:620px;margin:0 auto;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden">
        <div style="background:#2563eb;padding:18px 22px">
          <h2 style="color:#fff;margin:0;font-size:18px">🌐 New Visitor Logged</h2>
          <p style="color:#bfdbfe;margin:4px 0 0;font-size:13px">${visitedAt}</p>
        </div>
        <table style="width:100%;border-collapse:collapse">
          ${row('🌍 Country',     country)}
          ${row('🗺️ State',       state)}
          ${row('🏙️ City',        city)}
          ${row('📱 Device',      deviceType)}
          ${row('💻 Platform',    platform)}
          ${row('🌐 Language',    language)}
          ${row('⏰ Timezone',    timezone)}
          ${row('🔗 Referrer',    referrer || '(direct)')}
          ${row('📄 Current URL', currentUrl)}
          ${row('🖥️ IP Address',  ip)}
          ${row('🔍 User Agent',  uaString)}
        </table>
        <p style="font-size:11px;color:#9ca3af;padding:12px 16px;margin:0;background:#f9fafb">
          Auto-generated by Visitor Tracking System
        </p>
      </div>
    `,
  };

  const response = await axios.post(
    'https://api.brevo.com/v3/smtp/email',
    payload,
    {
      headers: {
        'api-key':      process.env.BREVO_API_KEY,
        'Content-Type': 'application/json',
        'Accept':       'application/json',
      },
    }
  );

  return response.data;
}

// ─── POST /api/viewer ─────────────────────────────────────────────────────────
router.post('/', async (req, res) => {
  try {
    const { currentUrl, referrer, language, platform, timezone } = req.body;

    // ── IP & Geo lookup ─────────────────────────────────────────────────────
    const rawIp = (
      req.headers['x-forwarded-for']?.split(',')[0].trim() ||
      req.socket.remoteAddress ||
      ''
    ).replace(/^::ffff:/, '');

    const geo      = geoip.lookup(rawIp) || {};
    const country  = geo.country || '';
    const state    = geo.region  || '';
    const province = geo.region  || '';
    const city     = geo.city    || '';

    // ── Parse User-Agent ────────────────────────────────────────────────────
    const uaString   = req.headers['user-agent'] || '';
    const deviceType = getDeviceType(uaString);

    // ── Current time (UTC) ──────────────────────────────────────────────────
    const now = new Date();

    // ── Insert row into DB ──────────────────────────────────────────────────
    const sql = `
      INSERT INTO "viewer" (
        country,        state,           province,
        "localDateTime","deviceType",    platform,
        timezone,       "userAgent",     language,
        referrer,       "currentUrl",    "timeVisitedUTC",
        "VisitDate",    city
      ) VALUES (
        $1,  $2,  $3,
        $4,  $5,  $6,
        $7,  $8,  $9,
        $10, $11, $12,
        $13, $14
      ) RETURNING *;
    `;

    const values = [
      country,          // $1  country
      state,            // $2  state
      province,         // $3  province
      now,              // $4  localDateTime (timestamptz)
      deviceType,       // $5  deviceType
      platform || '',   // $6  platform (from browser)
      now,              // $7  timezone (timestamptz column — stores UTC instant)
      uaString,         // $8  userAgent
      language || '',   // $9  language (from browser)
      referrer || '',   // $10 referrer (from browser)
      currentUrl || '', // $11 currentUrl (from browser)
      now,              // $12 timeVisitedUTC
      now,              // $13 VisitDate
      city,             // $14 city
    ];

    const { rows } = await pool.query(sql, values);
    const record   = rows[0];

    // ── Fire Brevo email — non-blocking ─────────────────────────────────────
    sendBrevoMail({
      country,
      state,
      city,
      deviceType,
      platform:   platform || '',
      language:   language || '',
      timezone:   timezone || '',
      referrer:   referrer || '',
      currentUrl: currentUrl || '',
      visitedAt:  now.toUTCString(),
      ip:         rawIp,
      uaString,
    }).catch((err) => {
      console.error('[brevo] Failed:', err?.response?.data || err.message);
    });

    return res.status(201).json({ success: true, id: record.Id });
  } catch (err) {
    console.error('[viewer] Error:', err);
    return res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

module.exports = router;